/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proj1;

import javax.swing.*;

/**
 *
 * @author Izaek Kisuule
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Dashboard() {
        initComponents();
        setTitle("Dashboard - Car Rental System");
        setSize(400, 400);
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar6 = new javax.swing.JMenuBar();
        menuManageCars = new javax.swing.JMenu();
        menuCars = new javax.swing.JMenuItem();
        menuCustomers = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuPayments = new javax.swing.JMenuItem();
        menuMaintenance = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        customerReport = new javax.swing.JMenuItem();
        carReport = new javax.swing.JMenuItem();
        rentalReport = new javax.swing.JMenuItem();
        paymentReport = new javax.swing.JMenuItem();
        maintenanceReport = new javax.swing.JMenuItem();
        menuFile = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar4.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar5.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar5.add(jMenu8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(127, 134, 103));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proj1/Rent-A-Car-Banner-22.jpg"))); // NOI18N

        menuManageCars.setText("System");

        menuCars.setText("ManageCars");
        menuCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCarsActionPerformed(evt);
            }
        });
        menuManageCars.add(menuCars);

        menuCustomers.setText("Manage Customers");
        menuCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCustomersActionPerformed(evt);
            }
        });
        menuManageCars.add(menuCustomers);

        jMenuItem3.setText("Manage Rentals");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuManageCars.add(jMenuItem3);

        menuPayments.setText("Manage Payments");
        menuPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPaymentsActionPerformed(evt);
            }
        });
        menuManageCars.add(menuPayments);

        menuMaintenance.setText("Vehicle Mantenance");
        menuMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMaintenanceActionPerformed(evt);
            }
        });
        menuManageCars.add(menuMaintenance);

        jMenuItem6.setText("jMenuItem6");
        menuManageCars.add(jMenuItem6);

        jMenuBar6.add(menuManageCars);

        jMenu9.setText("Reports");

        customerReport.setText("Customer Report");
        customerReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerReportActionPerformed(evt);
            }
        });
        jMenu9.add(customerReport);

        carReport.setText("Car Inventory Report");
        carReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carReportActionPerformed(evt);
            }
        });
        jMenu9.add(carReport);

        rentalReport.setText("Rental Report");
        rentalReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalReportActionPerformed(evt);
            }
        });
        jMenu9.add(rentalReport);

        paymentReport.setText("Payment Report");
        paymentReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentReportActionPerformed(evt);
            }
        });
        jMenu9.add(paymentReport);

        maintenanceReport.setText("Maintenance Report");
        maintenanceReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceReportActionPerformed(evt);
            }
        });
        jMenu9.add(maintenanceReport);

        jMenuBar6.add(jMenu9);

        menuFile.setText("File");

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        jMenuBar6.add(menuFile);

        setJMenuBar(jMenuBar6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void maintenanceReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceReportActionPerformed
        // TODO add your handling code here:
        ReportGenerator.generateMaintenanceReport();
    }//GEN-LAST:event_maintenanceReportActionPerformed

    private void customerReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerReportActionPerformed
        // TODO add your handling code here:
        ReportGenerator.generateCustomerReport();
    }//GEN-LAST:event_customerReportActionPerformed

    private void carReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carReportActionPerformed
        // TODO add your handling code here:
        ReportGenerator.generateCarReport();
    }//GEN-LAST:event_carReportActionPerformed

    private void rentalReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalReportActionPerformed
        // TODO add your handling code here:
        String startDate = JOptionPane.showInputDialog(this, "Enter start date (YYYY-MM-DD):");
        String endDate = JOptionPane.showInputDialog(this, "Enter end date (YYYY-MM-DD):");
        if (startDate != null && endDate != null) {
            ReportGenerator.generateRentalReport(startDate, endDate);
        }
    }//GEN-LAST:event_rentalReportActionPerformed

    private void paymentReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentReportActionPerformed
        // TODO add your handling code here:
        ReportGenerator.generatePaymentReport();
    }//GEN-LAST:event_paymentReportActionPerformed

    private void menuCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCarsActionPerformed
        this.dispose();
        new VehicleMgt().setVisible(true);
    }//GEN-LAST:event_menuCarsActionPerformed

    private void menuCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCustomersActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CustomerManagement().setVisible(true);
    }//GEN-LAST:event_menuCustomersActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CarAssignment().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPaymentsActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Payment().setVisible(true);
    }//GEN-LAST:event_menuPaymentsActionPerformed

    private void menuMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMaintenanceActionPerformed
        this.dispose();
        new VehicleMantenance().setVisible(true);
    }//GEN-LAST:event_menuMaintenanceActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem carReport;
    private javax.swing.JMenuItem customerReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem maintenanceReport;
    private javax.swing.JMenuItem menuCars;
    private javax.swing.JMenuItem menuCustomers;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuMaintenance;
    private javax.swing.JMenu menuManageCars;
    private javax.swing.JMenuItem menuPayments;
    private javax.swing.JMenuItem paymentReport;
    private javax.swing.JMenuItem rentalReport;
    // End of variables declaration//GEN-END:variables
}
